name: self tests

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - v03

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:

  run_sr_insects_tests:

    strategy:
      # Don't cancel the entire matrix when one job fails
      fail-fast: false
      matrix:
       which_test: [ shim ]
       #osver: [ "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04" ]
       osver: [ "ubuntu-22.04" ]

    runs-on: ${{ matrix.osver }}
  
    name: ${{ matrix.which_test }} test on ${{ matrix.osver }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          ./vm_autoconfig.sh
          ./vm_ssh_localhost.sh
         
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event.inputs.debug_enabled }}
        #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Setup ${{ matrix.which_test }} build binaries.
        run: |
          echo hoho
          make 

      - name: Setup ${{ matrix.which_test }} run unit tests
        run: |
          make trust_but_verify

      - name: Setup ${{ matrix.which_test }} run shim tests
        run: |
          make test_shim
