name: self tests

on:

  pull_request:
    types: [opened, edited, reopened]

  push:
    branches:
      - development
      - stable

    paths-ignore:
      - '.github/**'
      - 'debian/changelog'
      - 'TODO.txt'

  workflow_dispatch:

jobs:

  run_sr_insects_tests:

    strategy:
      # Don't cancel the entire matrix when one job fails
      fail-fast: false
      matrix:
       which_test: [ unit ]
       osver: [ "ubuntu-20.04", "ubuntu-22.04" ]

    runs-on: ${{ matrix.osver }}
  
    name: ${{ matrix.which_test }} test on ${{ matrix.osver }}
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          ./vm_autoconfig.sh
          ./vm_ssh_localhost.sh
         
      - name: Setup ${{ matrix.which_test }} build binaries.
        run: |
          make 

      - name: Setup ${{ matrix.which_test }} run unit tests
        run: |
          make trust_but_verify
